### ISSUE TITLE
We need a logo

### ISSUE THREAD

**Issue by iimog** [molbiodiv/bcdatabaser#24]
In my opinion a logo is very important for any tool :smiley:
Unfortunately I'm not a good artist or designer. Nevertheless I want to throw a first suggestion in but I highly encourage @sonjahohlfeld and @chiras to comment, improve or create something completely different.
![logo](https://user-images.githubusercontent.com/7403236/59604224-d4100c00-910b-11e9-8baa-92f1d9096b18.png)

**Comment by mirzazulfan** [comment]
Hi @iimog what do you think about this? Best regard.
![dbcreator](https://user-images.githubusercontent.com/36124339/60006239-3af86c80-969a-11e9-8a23-42b7fa4fe97b.png)

**Comment by iimog** [comment]
Wow @mirzazulfan super cool! I like it a lot. So you would be willing to grant us permission to use that as the logo? If we use it or any derivative of it we credit you with creation of the logo in a dedicated section of the README. Is that fine for you?

**Comment by mirzazulfan** [comment]
I'm glad you liked it. What color do you like? I will send all files and editables file. Regard.

**Comment by iimog** [comment]
Awesome! I slightly prefer the blue version.

**Comment by mirzazulfan** [comment]
I've created a pr #25 , If you need help in future please let me know.

**Comment by mirzazulfan** [comment]
Hi @iimog you can download all files [here](https://drive.google.com/drive/folders/1LFmMh_SB2HaK8xrwXJzuez1p6TGAxuZ9) Regard!

**Comment by iimog** [comment]
Thank you so much. I plan to merge the pr later today. I want to add the attribution section to the README before I do so.

**Comment by iimog** [comment]
We have one now :smiley:
