### ISSUE TITLE
how to update the taxonomy database

### ISSUE THREAD

**Issue by TomaszSuchan** [molbiodiv/bcdatabaser#33]
Hi, could you please provide some information in the documentation on how to update the local taxonomy database when using bcdatabaser docker image?

**Comment by iimog** [comment]
Hi, the easiest way to achieve this is to manually build the docker image. Clone the repository and run `docker build -t bcdatabaser .` inside it. The taxonomy databases are updated as part of the build process (this happens in two locations, once for the `NCBI::Taxonomy` perl module [Dockerfile#L10](https://github.com/molbiodiv/bcdatabaser/blob/master/Dockerfile#L10) and once for Krona [Dockerfile#L21](https://github.com/molbiodiv/bcdatabaser/blob/master/Dockerfile#L21)). 

I also triggered a rebuild on DockerHub but this one is still pending. But you should be able to get an up-to-date image tomorrow using `docker pull iimog/bcdatabaser`.

**Comment by TomaszSuchan** [comment]
Hi Markus, thanks for a quick response!

**Comment by iimog** [comment]
My pleasure. The build on DockerHub is finished. Let me know if you have other questions.
