### ISSUE TITLE
Geographic range

### ISSUE THREAD

**Issue by BWobbii** [molbiodiv/bcdatabaser#34]
would be great to include a filter by geography option, e.g. all hymenoptera from germany

**Comment by iimog** [comment]
I think this is a great suggestion. Unfortunately, we currently filter by creating a query string for NCBI and I'm afraid there is no option for this from their side. So it is not something we can easily support. We would need to get this list from some third party service, like GBIF. Won't be easy but is probably useful to many users.

**Comment by chiras** [comment]
Indeed, would be a good feature, but there is also a scientific reason why we would not implement that.

Just to add to the reply @iimog gave to the technical side: There is for some reference sequence data geographical information available, but to subset on those would bring the issue that the same species might also be present in other regions and will be ignored in such analyses then. 

So our approach is that species lists are used as filter, which can be country lists. In most cases, the researchers can provide better taxon lists for their system of interest, as we could with a generic list of species occurrences in countries (i.e. validated species checklists, own diversity assessments, monitoring campaigns, etc.). In case such are not available, species occurrence lists can also be downloaded to from GBIF (with less validation though) or other sources: 

[https://www.gbif.org/occurrence/search?country=DE&taxon_key=1457&occurrence_status=present](https://www.gbif.org/occurrence/search?country=DE&taxon_key=1457&occurrence_status=present) 
This would equal your request of Hymenoptera in Germany. 

This species occurrence list can be made cleaned up and made uniq e.g. with this bash code:
`cut -f 2 occurence_data.csv | sed -e "s/^\([a-zA-Z-]\{2,30\}\) \([a-zA-Z-]\{2,30\}\).*$/\1 \2/" -e "/scientificName/d" | sed -e "/\./d" -e "/^[a-zA-Z]*$/d" -e "/^[a-zA-Z]\{2,30\} [A-Z]/d"  -e "/\?/d"  -e "/×/d" | sort | uniq > bcdatabaser_input.txt`
and then fed into bcdatabaser.
